version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - springnet
    volumes:
      - ./src/main/resources/logback.xml:/app/resources/logback.xml
      

  db:
    image: postgres:15
    container_name: post-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springnet
volumes:
  pgdata:
  

networks:
  springnet:
    driver: bridge






